use Mix.Config

# Configure your database
config :simple_request, SimpleRequest.Repo,
  username: "postgres",
  password: "postgres",
  database: "simple_request_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :simple_request, SimpleRequestWeb.Endpoint,
  http: [port: 3333],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

config :simple_request, SimpleRequest.PromEx,
  manual_metrics_start_delay: :no_delay,
  drop_metrics_groups: [],
  grafana: [
    host: System.get_env("GRAFANA_HOST", "http://localhost:3000"),
    # auth_token: System.get_env("GRAFANA_TOKEN", ""),
    username: "admin",
    password: "admin",
    upload_dashboards_on_start: true,
    folder_name: "Web App Dashboards",
    annotate_app_lifecycle: true
  ]

# ,
# metrics_server: [
#   port: 9090,
#   path: "/metrics",
#   protocol: :http,
#   pool_size: 5,
#   cowboy_opts: []
# ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
