# Global Configurations
global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'simple_request'

# Targets to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'simple_request'
    static_configs:
      - targets: ['172.17.0.1:3333']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['172.17.0.1:9187']
